In [1]:
import pandas as pd 
import numpy as np

In [2]:
# 匯入EURUSD的數據資料
df = pd.read_csv('./Pre_data/conbine_data/EURUSD105_109.csv', index_col=0)

In [3]:
#資料框樣子
df

,date,word2vec_body,tfidf_body,bert_body,source_title,binary,ternary_1,ternary_2
0,2016-01-01,unemployment continues to fall inflation is in...,unemployment continue fall inflation check int...,['unemployment continues to fall inflation is ...,Forbes,0.0,0.0,0.0
1,2016-01-01,was a year of tremendous political and econom...,year tremendous political economic volatility ...,[' was a year of tremendous political and econ...,Forbes,0.0,0.0,0.0
2,2016-01-01,riverside co is ringing in the new year with i...,riverside co ring new year late acquisition re...,['riverside co is ringing in the new year with...,The Wall Street Journal,0.0,0.0,0.0
3,2016-01-01,distrust in banking system hinders capital con...,distrust banking system hinders capital contro...,['distrust in banking system hinders capital c...,Bloomberg Business,0.0,0.0,0.0
4,2016-01-01,in the years since a peace treaty was signed i...,year since peace treaty sign belfast end three...,['in the years since a peace treaty was signed...,International Business Times,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
101552,2020-12-31,i write about energy and commodities from rene...,write energy commodity renewable energy coal h...,['i write about energy and commodities from re...,Forbes,0.0,0.0,0.0
101553,2020-12-31,philanthropic endeavors are nothing new to the...,philanthropic endeavor nothing new watch indus...,['philanthropic endeavors are nothing new to t...,MarketWatch,0.0,0.0,0.0
101554,2020-12-31,wall street indices finished at alltime highs ...,wall street index finish alltime high thursday...,['wall street indices finished at alltime high...,International Business Times,0.0,0.0,0.0
101555,2020-12-31,the us dollar went from life preserver to cast...,u dollar go life preserver castaway topsyturvy...,['the us dollar went from life preserver to ca...,MarketWatch,0.0,0.0,0.0
101556,2020-12-31,in september surveying the ruins of a continen...,september survey ruin continent rip apart war ...,['in september surveying the ruins of a contin...,International Business Times,0.0,0.0,0.0

In [4]:
#把沒要用的來源去掉
index1 = df[df["source_title"]=="Business Insider"].index
index2 = df[df["source_title"]=="Forbes"].index
index3 = df[df["source_title"]=="International Business Times"].index
index4 = df[df["source_title"]=="The Motley Fool"].index
index5 = df[df["source_title"]=="The Wall Street Journal"].index

df = df.drop(index1)
df = df.drop(index2)
df = df.drop(index3)
df = df.drop(index4)
df = df.drop(index5)
df = df.reset_index(drop=True)
df

,date,word2vec_body,tfidf_body,bert_body,source_title,binary,ternary_1,ternary_2
0,2016-01-01,distrust in banking system hinders capital con...,distrust banking system hinders capital contro...,['distrust in banking system hinders capital c...,Bloomberg Business,0.0,0.0,0.0
1,2016-01-01,it is trades for the new year the fast money...,trade new year fast money trader give trade ma...,"['it is ', ' trades for the new year the fast...",CNBC,0.0,0.0,0.0
2,2016-01-02,profit growth monetary policy to spur further ...,profit growth monetary policy spur outperforma...,['profit growth monetary policy to spur furthe...,Bloomberg Business,0.0,0.0,0.0
3,2016-01-02,taipei taiwan dec prnewswire heraeus photovol...,taipei taiwan dec prnewswire heraeus photovolt...,['taipei taiwan dec prnewswire heraeus photov...,MarketWatch,0.0,0.0,0.0
4,2016-01-02,summary poor inflation shaky business confide...,summary poor inflation shaky business confiden...,['summary poor inflation shaky business confi...,Seeking Alpha,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
74870,2020-12-31,in an eventful year for global markets some in...,eventful year global market individual one com...,['in an eventful year for global markets some ...,Financial Times,0.0,0.0,0.0
74871,2020-12-31,british airways will be temporarily barred fro...,british airway temporarily bar pay dividend pa...,['british airways will be temporarily barred f...,Financial Times,0.0,0.0,0.0
74872,2020-12-31,myt netherlands parent bv myte parent company ...,myt netherlands parent bv myte parent company ...,['myt netherlands parent bv myte parent compan...,MarketWatch,0.0,0.0,0.0
74873,2020-12-31,philanthropic endeavors are nothing new to the...,philanthropic endeavor nothing new watch indus...,['philanthropic endeavors are nothing new to t...,MarketWatch,0.0,0.0,0.0
74874,2020-12-31,the us dollar went from life preserver to cast...,u dollar go life preserver castaway topsyturvy...,['the us dollar went from life preserver to ca...,MarketWatch,0.0,0.0,0.0

In [5]:
df.to_csv("./Pre_data/move_window/EUR/EUR0.csv")

### 下面先不要做

In [5]:
# 訓練:45個月
# 驗證:5個月
# 測試:5個月

#1

star = df["date"]>="2016-01-01"
end = df["date"]<"2020-07-01"
sub1 = df[(star & end)]
sub1

,date,word2vec_body,tfidf_body,bert_body,source_title,binary,ternary_1,ternary_2
0,2016-01-01,distrust in banking system hinders capital con...,distrust banking system hinders capital contro...,['distrust in banking system hinders capital c...,Bloomberg Business,0.0,0.0,0.0
1,2016-01-01,it is trades for the new year the fast money...,trade new year fast money trader give trade ma...,"['it is ', ' trades for the new year the fast...",CNBC,0.0,0.0,0.0
2,2016-01-02,profit growth monetary policy to spur further ...,profit growth monetary policy spur outperforma...,['profit growth monetary policy to spur furthe...,Bloomberg Business,0.0,0.0,0.0
3,2016-01-02,taipei taiwan dec prnewswire heraeus photovol...,taipei taiwan dec prnewswire heraeus photovolt...,['taipei taiwan dec prnewswire heraeus photov...,MarketWatch,0.0,0.0,0.0
4,2016-01-02,summary poor inflation shaky business confide...,summary poor inflation shaky business confiden...,['summary poor inflation shaky business confi...,Seeking Alpha,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
66658,2020-06-30,the morgan stanley global franchise fund has r...,morgan stanley global franchise fund release f...,['the morgan stanley global franchise fund has...,Yahoo Finance,0.0,2.0,2.0
66659,2020-06-30,the europas has previously awarded innovative ...,europa previously award innovative startup lik...,['the europas has previously awarded innovativ...,Yahoo Finance,0.0,2.0,2.0
66660,2020-06-30,the bank for international settlements bis wil...,bank international settlement bis establish fo...,['the bank for international settlements bis w...,Yahoo Finance,0.0,2.0,2.0
66661,2020-06-30,how has the coronavirus pandemic changed peopl...,coronavirus pandemic change people perception ...,['how has the coronavirus pandemic changed peo...,Bloomberg Business,0.0,2.0,2.0
66662,2020-06-30,deal for largest european lbo in decade arrang...,deal large european lbo decade arrange virus h...,['deal for largest european lbo in decade arra...,Bloomberg Business,0.0,2.0,2.0

In [8]:
sub1.to_csv("./Pre_data/move_window/EUR/EUR1.csv")

In [6]:
#2
star = df["date"]>="2016-04-01"
end = df["date"]<"2020-10-01"
sub2 = df[(star & end)]
sub2

,date,word2vec_body,tfidf_body,bert_body,source_title,binary,ternary_1,ternary_2
2465,2016-04-01,jim cramer provides his thoughts on why invest...,jim cramer provide thought investor stay cauti...,['jim cramer provides his thoughts on why inve...,CNBC,1.0,1.0,2.0
2466,2016-04-01,pilot program aimed at easing affordablehousin...,pilot program aim ease affordablehousing compl...,['pilot program aimed at easing affordablehous...,MarketWatch,1.0,1.0,2.0
2467,2016-04-01,copper buoyed as official china manufacuring i...,copper buoy official china manufacuring index ...,['copper buoyed as official china manufacuring...,Bloomberg Business,1.0,1.0,2.0
2468,2016-04-01,deutsche bank changes compensation system for ...,deutsche bank change compensation system divis...,['deutsche bank changes compensation system fo...,Bloomberg Business,1.0,1.0,2.0
2469,2016-04-01,apm terminals ceo says company has clout to bu...,apm terminal ceo say company clout buy amid do...,['apm terminals ceo says company has clout to ...,Bloomberg Business,1.0,1.0,2.0
...,...,...,...,...,...,...,...,...
71471,2020-09-30,bayer otcpkbayry shares turn sharply lower aft...,bayer otcpkbayry share turn sharply low compan...,['bayer otcpkbayry shares turn sharply lower a...,Seeking Alpha,0.0,0.0,2.0
71472,2020-09-30,bayer ag plans to cut billion euros billion of...,bayer ag plan cut billion euro billion annual ...,['bayer ag plans to cut billion euros billion ...,Bloomberg Business,0.0,0.0,2.0
71473,2020-09-30,amy sullivan senior vice president corporate a...,amy sullivan senior vice president corporate a...,['amy sullivan senior vice president corporate...,Seeking Alpha,0.0,0.0,2.0
71474,2020-09-30,at the close dow to sp to nasdaq to treasury f...,close dow sp nasdaq treasury future year yr yr...,['at the close dow to sp to nasdaq to treasury...,Seeking Alpha,0.0,0.0,2.0
71475,2020-09-30,editor is note seeking alpha is proud to welco...,editor note seek alpha proud welcome warren lu...,['editor is note seeking alpha is proud to wel...,Seeking Alpha,0.0,0.0,2.0

In [9]:
sub2.to_csv("./Pre_data/move_window/EUR/EUR2.csv")

In [7]:
#3
star = df["date"]>="2016-07-01"
end = df["date"]<"2021-01-01"
sub3 = df[(star & end)]
sub3

,date,word2vec_body,tfidf_body,bert_body,source_title,binary,ternary_1,ternary_2
5924,2016-07-01,joining the european economic area would be an...,join european economic area would obvious way ...,['joining the european economic area would be ...,Bloomberg Business,1.0,1.0,1.0
5925,2016-07-01,some investors are flocking to asian fixed inc...,investor flock asian fixed income asset lure p...,['some investors are flocking to asian fixed i...,CNBC,1.0,1.0,1.0
5926,2016-07-01,sydney reuters china is factories flatlined in...,sydney reuters china factory flatlined june ex...,['sydney reuters china is factories flatlined ...,Yahoo Finance,1.0,1.0,1.0
5927,2016-07-01,the european commission has authorized an ital...,european commission authorize italian governme...,['the european commission has authorized an it...,CNBC,1.0,1.0,1.0
5928,2016-07-01,london reuters sterling fell on friday dragged...,london reuters sterling fell friday drag expec...,['london reuters sterling fell on friday dragg...,Yahoo Finance,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...
74870,2020-12-31,in an eventful year for global markets some in...,eventful year global market individual one com...,['in an eventful year for global markets some ...,Financial Times,0.0,0.0,0.0
74871,2020-12-31,british airways will be temporarily barred fro...,british airway temporarily bar pay dividend pa...,['british airways will be temporarily barred f...,Financial Times,0.0,0.0,0.0
74872,2020-12-31,myt netherlands parent bv myte parent company ...,myt netherlands parent bv myte parent company ...,['myt netherlands parent bv myte parent compan...,MarketWatch,0.0,0.0,0.0
74873,2020-12-31,philanthropic endeavors are nothing new to the...,philanthropic endeavor nothing new watch indus...,['philanthropic endeavors are nothing new to t...,MarketWatch,0.0,0.0,0.0
74874,2020-12-31,the us dollar went from life preserver to cast...,u dollar go life preserver castaway topsyturvy...,['the us dollar went from life preserver to ca...,MarketWatch,0.0,0.0,0.0

In [10]:
sub3.to_csv("./Pre_data/move_window/EUR/EUR3.csv")

#### 儲存滑動視窗資料

In [5]:
import time

staryear = 105
endyear = 108
allmonth = (endyear-staryear+1)*12   #所有的月份資料的總數 -> 60
winsize = 12    #滑動月份大小 (訓練加測試3:1) 訓練75% : 測試25%

training_score = [] #用來儲存訓練結果
testing_score = [] #用來儲存測試結果

#滑動視窗設立變數
sy = 16 #起始年
ey = 17 #結束年
ty = 16 #訓練年
sm0 = 0 #起始月十位數
sm1 = 1 #起始月個位數
em0 = 0 #結束月十位數
em1 = 1 #結束月個位數
tm0 = 1 #訓練月十位數
tm1 = 2 #訓練月個位數

#滑動視窗開始
for z in range(allmonth-winsize):
    
    start = time.time()
    
    #條件判斷(這判斷之累QQQQ)
    if sm1 >= 10:
        if sm0 == 0:
            sm0 = 1
            if sm1 == 10:
                sm1 = 0
            elif sm1 == 11:
                sm1 = 1
            elif sm1 == 12:
                sm1 = 2
            elif sm1 == 13:
                sm1 = 3
        if sm0 == 1:
            if sm1 >= 3:
                sm0 = 0
                sm1 = 1
                sy += 1
                
    if em1 >= 10:
        if em0 == 0:
            em0 = 1
            if em1 == 10:
                em1 = 0
            elif em1 == 11:
                em1 = 1
            elif em1 == 12:
                em1 = 2
            elif em1 == 13:
                em1 = 3
        if em0 == 1:
            if em1 >= 3:
                em0 = 0
                em1 = 1
                ey += 1
                
    if tm1 >= 10:
        if tm0 == 0:
            tm0 = 1
            if tm1 == 10:
                tm1 = 0
            elif tm1 == 11:
                tm1 = 1
            elif tm1 == 12:
                tm1 = 2
            elif tm1 == 13:
                tm1 = 3
        if tm0 == 1:
            if tm1 >= 3:
                tm0 = 0
                tm1 = 1
                ty += 1
        
    #滑動視窗遮罩    
    start = '20%d-%d%d-01' %(sy, sm0, sm1)
    end = '20%d-%d%d-01' %(ey, em0, em1)
    test = '20%d-%d%d-01' %(ty, tm0, tm1)
    
    mask1 = df['date'] >= start
    mask2 = df['date'] < end
    
    #取出滑動視窗範圍資料
    win_df = df[(mask1 & mask2)]
    win_df = win_df.reset_index(drop=True)
    
    #每個滑動視窗各自儲存
    win_df.to_csv("./Pre_data/move_window/EUR_12/"+str(z)+".csv",index = 0)
    
    #條件判斷
    if sm0 == 1:
        sm1 = 10 * sm0 + sm1
        sm0 = 0
    if em0 == 1:
        em1 = 10 * em0 + em1
        em0 = 0
    if tm0 == 1:
        tm1 = 10 * tm0 + tm1
        tm0 = 0
    
    #視窗滑動
    em1 += 1
    sm1 += 1
    tm1 += 1
    print("滑動視窗"+str(z)+"大小:{}".format(win_df.shape))
    print('=============================')

滑動視窗0大小:(20901, 9)
=============================
滑動視窗1大小:(20714, 9)
=============================
滑動視窗2大小:(20236, 9)
=============================
滑動視窗3大小:(19708, 9)
=============================
滑動視窗4大小:(19102, 9)
=============================
滑動視窗5大小:(18727, 9)
=============================
滑動視窗6大小:(17195, 9)
=============================
滑動視窗7大小:(16194, 9)
=============================
滑動視窗8大小:(15662, 9)
=============================
滑動視窗9大小:(15312, 9)
=============================
滑動視窗10大小:(14966, 9)
=============================
滑動視窗11大小:(14441, 9)
=============================
滑動視窗12大小:(13584, 9)
=============================
滑動視窗13大小:(13875, 9)
=============================
滑動視窗14大小:(14323, 9)
=============================
滑動視窗15大小:(15008, 9)
=============================
滑動視窗16大小:(15591, 9)
=============================
滑動視窗17大小:(16553, 9)
=============================
滑動視窗18大小:(17320, 9)
=============================
滑動視窗19大小:(18026, 9)
=============================
滑動視窗20大小:(18957, 9)
=============================
滑動視窗21大小:(19358, 9)
=============================
滑動視窗22大小:(20045, 9)
=============================
滑動視窗23大小:(21113, 9)
=============================
滑動視窗24大小:(21732, 9)
=============================
滑動視窗25大小:(21780, 9)
=============================
滑動視窗26大小:(21419, 9)
=============================
滑動視窗27大小:(20824, 9)
=============================
滑動視窗28大小:(20646, 9)
=============================
滑動視窗29大小:(19879, 9)
=============================
滑動視窗30大小:(19292, 9)
=============================
滑動視窗31大小:(19260, 9)
=============================
滑動視窗32大小:(18782, 9)
=============================
滑動視窗33大小:(20140, 9)
=============================
滑動視窗34大小:(21123, 9)
=============================
滑動視窗35大小:(21922, 9)
=============================